# Generated by Django 4.0.2 on 2022-05-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GEOPointCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(help_text='time stamp of measurement', verbose_name='Момент замера')),
                ('lat', models.FloatField(help_text='latitude', verbose_name='Широта')),
                ('lng', models.FloatField(help_text='longitude', verbose_name='Долгота')),
                ('co2', models.FloatField(verbose_name='Уровень CO2 в воздухе')),
            ],
        ),
    ]
